image: adoptopenjdk:11-jdk-hotspot

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle_home
  KONAN_DATA_DIR: $CI_PROJECT_DIR/.konan_home

before_script:
  - rm -f $GRADLE_USER_HOME/caches/modules-2/modules-2.lock
  - rm -f $GRADLE_USER_HOME/caches/build-cache-1/build-cache-1.lock

cache:
  key: one-key-to-rule-them-all
  paths:
    - $GRADLE_USER_HOME/wrapper/dists/
    - $GRADLE_USER_HOME/caches/modules-2/
    - $GRADLE_USER_HOME/caches/build-cache-1/

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
